### ISSUE TITLE
FATAL EXCEPTION: pool-1-thread-1

### ISSUE THREAD

**Issue by verysi** [KasemJaffer/media_picker_builder#1]
When I execute the function ‘MediaPickerBuilder.getThumbnail(fileId: id, type: type, );’, the program will report an error.
Console information;
'E/AndroidRuntime( 8716): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime( 8716): Process: com.sisi.lovemusic, PID: 8716
E/AndroidRuntime( 8716): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-1-thread-1'

**Comment by samonkoba** [comment]
Any update on this issue, Builder crashes app while loading media

**Comment by samonkoba** [comment]
It seems with the update to flutter several things might have changed. I fixed the issue on my side by adding a Looper Handler to MediaPickerBuilderPlugin class upon results like so.

`                     val mainHandler:Handler = Handler(context.getMainLooper());`
`                     val runnable:Runnable = object: Runnable{`
`                        override fun run(){`
`                            if (thumbnail != null)`
`                               result.success(thumbnail)`
`                            else`
`                                result.error("NOT_FOUND", "Unable to get the thumbnail", null)`
`                        }`
`                    };`

**Comment by lifenautjoe** [comment]
Hi @KasemJaffer , any chance you can take a look at this?

**Comment by miquelbeltran** [comment]
FYI, if you copy the solution from @samonkoba , remember to call 

```
mainHandler.post(runnable)
```

Or if you need a temporal solution, you can use my fork:

```
  media_picker_builder:
    git: https://github.com/miquelbeltran/media_picker_builder.git
```

which contains @samonkoba solution.

I'd prefer that you @samonkoba send the pull request as you came up with the solution, but if you don't I am happy to do that.

**Comment by samonkoba** [comment]
@miquelbeltran Please do. I'm not able at the moment

**Comment by KasemJaffer** [comment]
Sorry for the late reply, I have been very busy lately couldn't look into the issues filed. Good new though, I just published a fix based on @miquelbeltran 's pull request `media_picker_builder: ^1.2.0+2`

**Comment by lifenautjoe** [comment]
Thanks Kasem!
