### ISSUE TITLE
Android 10 failing to load thumbnail paths

### ISSUE THREAD

**Issue by miquelbeltran** [KasemJaffer/media_picker_builder#4]
Since I switched to Android 10 on my device, the library is failing to fetch the thumbnail paths.

Debugging I can see that the `generateThumbnail` method is correctly generating a Bitmap, however the content resolver query is returning an empty cursor:

```
                    context.contentResolver.query(
                            MediaStore.Images.Thumbnails.EXTERNAL_CONTENT_URI,
                            arrayOf(MediaStore.Images.Thumbnails.DATA),
                            "${MediaStore.Images.Thumbnails.IMAGE_ID} = $fileId"
                                    + " AND ${MediaStore.Images.Thumbnails.KIND} = ${MediaStore.Images.Thumbnails.MINI_KIND}",
                            null,
                            null)?.use { cursor ->

// cursor is always empty

                        if (cursor.count > 0) {
                            cursor.moveToFirst()
                            path = cursor.getString(0)
                        }
                    }
```

I am testing with a Pixel 3a with Android 10.

**Comment by KasemJaffer** [comment]
Sorry about that I am working on it

**Comment by KasemJaffer** [comment]
Fixed now in version 1.2.2

**Comment by miquelbeltran** [comment]
thanks for the fix!

**Comment by MukulKumar09** [comment]
Not related to media_picker_builder, how does this work? I know contentresolver has loadThumbnail now. But I just want path of the thumbnail. And MediaStore.Images.Thumbnails.EXTERNAL_CONTENT_URI is returning empty cursor to me.
